//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFinanceiroAPI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.Compra = new HashSet<Compra>();
        }

        public int CategoriaID { get; set; }
        public string Nome { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }

        public CategoriasDTO toDTO()
        {
            CategoriasDTO categoriaDTO = new CategoriasDTO()
            {
                CategoriaID = this.CategoriaID,
                Nome = this.Nome
            };

            return categoriaDTO;
        }

        
    }
}
