//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ControleFinanceiroAPI.Models;

namespace ControleFinanceiroAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int CompraID { get; set; }
        public int CategoriaID { get; set; }
        public int EstabelecimentoID { get; set; }
        public System.DateTime Data { get; set; }
        public float Valor { get; set; }


        public virtual Categoria Categoria { get; set; }
        public virtual Estabelecimento Estabelecimento { get; set; }

        public ComprasDTO toDTO()
        {

            ComprasDTO compraDTO = new ComprasDTO()
            {
                CompraID = this.CompraID,
                CategoriaID = this.Categoria.CategoriaID,
                CategoriaNome = this.Categoria.Nome,
                EstabelecimentoID = this.Estabelecimento.EstabelecimentoID,
                EstabelecimentoNome = this.Estabelecimento.Nome,
                Data = this.Data,
                Valor = this.Valor
            };

            return compraDTO;
        }
    }
}
