//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFinanceiroAPI.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Estabelecimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estabelecimento()
        {
            this.Compra = new HashSet<Compra>();
        }

        public int EstabelecimentoID { get; set; }
        public string Nome { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }

        public EstabelecimentosDTO toDTO()
        {
            EstabelecimentosDTO estabelimentoDTO = new EstabelecimentosDTO()
            {
                EstabelecimentoID = this.EstabelecimentoID,
                Nome = this.Nome
            };

            return estabelimentoDTO;
        }
    }
}
