//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleFinanceiroAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public Nullable<System.DateTime> DataHora { get; set; }
        public string Operacao { get; set; }
        public string Identificacao { get; set; }
        public int LogID { get; set; }
    }
}
